/**
 * Polymer-X: Zero-Cost Bioremediation Command Center
 * Core Type Definitions
 * 
 * These interfaces define the data contracts between the water analysis inputs
 * and the enzyme design outputs generated by the simulated Evo 2/RFdiffusion pipeline.
 */

/**
 * Input interface for water sample analysis.
 * Used to characterize the environmental conditions at a contamination site.
 */
export interface WaterAnalysis {
  /** Latitude coordinate of the sample location */
  lat: number;

  /** Longitude coordinate of the sample location */
  lng: number;

  /** Salinity level in parts per thousand (ppt). Seawater is typically ~35ppt */
  salinity: number;

  /** 
   * Type of plastic contamination detected.
   * PET = Polyethylene Terephthalate (bottles, containers)
   * HDPE = High-Density Polyethylene (pipes, bottles)
   * PVC = Polyvinyl Chloride (pipes, cable insulation)
   * LDPE = Low-Density Polyethylene (bags, films)
   * PP = Polypropylene (containers, automotive parts)
   * PS = Polystyrene (foam, packaging)
   */
  plastic_type: 'PET' | 'HDPE' | 'PVC' | 'LDPE' | 'PP' | 'PS';

  /** 
   * Boolean indicating if environmental stress signals are detected.
   * True = hostile conditions (extreme temp, pH, toxins)
   * False = normal environmental conditions
   */
  stress_signal_bool: boolean;
}

/**
 * Safety lock types for engineered organisms.
 * These are kill-switches that ensure biosafety.
 */
export type SafetyLockType = 
  | 'Quorum_Sensing_Type_A'   // Population density-based kill switch
  | 'Quorum_Sensing_Type_B'   // Enhanced population density control (REQUIRED per Zhang et al. 2025)
  | 'Temperature_Sensitive'   // Activated outside safe temperature range
  | 'Auxotrophic'             // Requires external nutrient to survive
  | 'Light_Activated';        // UV-triggered termination

/**
 * Chassis organism types for enzyme expression.
 */
export type ChassisType = 
  | 'Halophilic'      // Salt-tolerant (REQUIRED when salinity > 35ppt per Lee et al. 2025)
  | 'Mesophilic'      // Standard conditions
  | 'Thermophilic'    // Heat-tolerant
  | 'Psychrophilic';  // Cold-tolerant

/**
 * Output interface for enzyme design recommendations.
 * Generated by the simulated Evo 2 bio-agent based on WaterAnalysis inputs.
 */
export interface EnzymeDesign {
  /** Name of the designed enzyme (e.g., "PETase-v4.2-Halo") */
  enzyme_name: string;

  /** 
   * List of amino acid mutations applied to the base enzyme.
   * Format: [OriginalAA][Position][NewAA] (e.g., "S238F", "W159H")
   */
  mutation_list: string[];

  /** 
   * Predicted catalytic efficiency score (0.0 - 1.0).
   * Higher values indicate better plastic degradation performance.
   */
  predicted_efficiency_score: number;

  /** 
   * The biosafety mechanism integrated into the organism.
   * MUST include Quorum_Sensing_Type_B per Zhang et al. 2025 safety protocols.
   */
  safety_lock_type: SafetyLockType;

  /** Chassis organism selected for enzyme expression */
  chassis_type: ChassisType;

  /** Reasoning chain from the bio-agent explaining the design decisions */
  design_rationale: string;

  /** Reference citations supporting the design choices */
  references: string[];
}

/**
 * Configuration for the Gemini-based bio-agent simulation.
 */
export interface BioAgentConfig {
  /** Model identifier (e.g., "gemini-1.5-flash") */
  model: string;

  /** Temperature for response generation (0.0 - 1.0) */
  temperature: number;

  /** Maximum tokens in response */
  max_tokens: number;
}

/**
 * Response wrapper from the bio-agent service.
 */
export interface BioAgentResponse {
  /** Whether the simulation was successful */
  success: boolean;

  /** The generated enzyme design, if successful */
  data?: EnzymeDesign;

  /** Error message if simulation failed */
  error?: string;

  /** Timestamp of the response */
  timestamp: string;
}
